var age;
var names;
var toggle;
var empty;
var notInitialize;
var callback;
age = 50;
names = 'Max';
toggle = true;
empty = null;
notInitialize = undefined;
callback = function (a) { return 100 + a; };
console.log('let age: number, let names: string, let toggle: boolean, let empty: null ,let notInitialize: undefined, let callback: (num: number) => void');
